name       : mate-icon-theme-faenza
version    : 1.20.0
release    : 3
source     :
    - https://github.com/mate-desktop-legacy-archive/mate-icon-theme-faenza/archive/v1.20.0.tar.gz : 3e838a08c18116d4d69fcacf50b456d79846db12bf249b44c7d971cf2df7b9c0
license    : GPL-2.0
component  : desktop.theme
summary    : MATE Desktop Faenza Icon Theme
description: |
    The faenza icon theme variant for the MATE Desktop
builddeps  :
    - mate-common
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
