name       : mate-icon-theme-faenza
version    : 1.18.1
release    : 1
source     :
    - http://pub.mate-desktop.org/releases/1.18/mate-icon-theme-faenza-1.18.1.tar.xz : 8920a19b5c1755bf3b489b3bf45b90d88e273825ff455a3ba83dfb42d3e3836d
license    : GPL-2.0
component  : desktop.theme
summary    : MATE Desktop Faenza Icon Theme
description: |
    The faenza icon theme variant for the MATE Desktop
builddeps  :
    - mate-common
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
